name: Build LaTeX to PDF

on:
  push:
    paths:
      - 'note/**.tex'
      - 'note/**.bib'
      - 'note/**.sty'
    branches:
      - main

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Pull latest changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git pull origin main --rebase --force

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v4
        with:
          working_directory: note/src
          root_file: "main.tex"
          # latexmk_use_xelatex: true
          

      - name: Move PDF to note
        run: |
          mv note/src/*.pdf note/

      - name: Commit and Push PDF
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "build: Update PDF [skip ci]"
          file_pattern: "**.pdf" 
